pid = /run/stunnel4/stunnel.pid
setuid = stunnel4
setgid = stunnel4

cert = /etc/stunnel/stunnel.pem
key  = /etc/stunnel/stunnel.pem

client = no
foreground = no

[stunnel-777]
accept = 0.0.0.0:777
connect = 127.0.0.1:700
